database:
  path: "syslens.db"

collection:
  interval_seconds: 30

thresholds:
  cpu_percent: 90
  memory_percent: 85
  disk_percent: 85

alerts:
  brute_force_attempts: 5
  brute_force_window_minutes: 10

whitelist_ports:
  - 22
  - 80
  - 443
  - 3306
  - 5432
  - 27017
  - 33060
  - 3389
  - 135
  - 139
  - 445
  - 5000
  - 8501
  - 8080
  - 11434
  - 49664
  - 49665
  - 49666
  - 49667
  - 49668
  - 49669
  - 5040
  - 3215
  - 3216
  - 3217